### PR TITLE
fix: emit error and prevent re-test

### PR DESCRIPTION
**Pull request by d3viant0ne**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Currently karma-webpack is swallowing fatal compilation errors which has a substantial negative effect on the development experience.

**What is the new behavior?**

- `karma-webpack: compiler.plugin` will throw on any `fatal compilation error`.
- `karma-webpack: compiler.plugin` will prevent re-running tests on the above condition.
- `karma-webpack: addEntry ` will not propagate errors for failed module imports.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the following...

* Impact:
* Migration path for existing applications:
* Github Issue(s) this is regarding:

> This needs to be tested with `@angular/cli` before it's merged.

Relates to: #49
Relates to: #66

### CODE REVIEW

**Comment by d3viant0ne** [comment]
Yeah, that's going to get done with the defaults upgrade.

**Comment by d3viant0ne** [comment]
@filipesilva - This should cover both of the plugins currently needed by `@angular/cli`. I'll get it merged & published after a few tests in one of my cli based apps.

**Comment by filipesilva** [comment]
Awesome, thanks so much for taking on this issue! I'll integrate it into the CLI after it's merged and released.

**Comment by filipesilva** [comment]
Let me test this on the CLI as well, as per your original comment.

**Comment by d3viant0ne** [comment]
From a DX perspective, would be a nice feature to provide an option to `pause` a test run on `ng test --someSpecificArg` for a fatal compilation error and allow a developer to fix the issue without having to recompile everything. 

Not that i'm suggesting that for now but it would certainly make TDD a bit nicer while using the cli.

**Comment by filipesilva** [comment]
This is the original commit where I used variations of the plugins in #49 and #66 to fix the error behaviour: https://github.com/angular/angular-cli/pull/5504/commits/8ab395410b0eb94aafeada4de28dff82517ca45a

The two cases we test for in the CLI are:
- on watch mode, rebuilds with errors will not rerun tests and instead wait to recompile
- on single run mode, builds with errors do not hang and exit with an error code

I tried the changes on this PR by applying them over the released version `2.0.3` and removing the custom plugins I had added:
- on watch mode, rebuilds with errors do not rerun tests **and exit the process with an error**
- on single run mode, builds with errors do not hang and exit with an error code

So I would say that the watch mode change is not ideal, since it requires users to re-run Karma on every error. The single-run mode is what we did though.

**Comment by d3viant0ne** [comment]
Give me 30 minutes & i'll fix the watch mode annoyance and properly cover those use cases covered.

`watch mode change is not ideal` ... it's down right obnoxious.

**Comment by d3viant0ne** [comment]
@filipesilva - Got dragged away.  After mulling this over for a while and in the spirit of not breaking apps that depend on karma-webpack or everyones CLI apps ( to include my own ) the right answer here imo is to just make this respect the `--bail` option like it should.

- Wouldn't break the litany of apps that have plugins applied to handle the bail problem.
- Change would be benign for the CLI on release ( given the version range in the cli )
- Would require a small PR into `@angular/cli` to update https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/plugins/karma.ts#L108 to just apply `bail: true` in `single run mode` and leave watch mode unaffected.

Assuming you don't mind a small PR into the CLI, i'll go the route above.

**Comment by filipesilva** [comment]
@d3viant0ne apologies for taking so long to get back to your message. I agree with the approach you've outlined, it's the best option overall. 

I was actually worried what direction it might take because of CLI version range, thank you for taking that into consideration 👍

**Comment by the-spyke** [comment]
Any news? Just spent almost an hour investigating a strange error in Karma. The root cause was in missing package in `node_modules`.

**Pull request closed without merging**
