### PR TITLE
fix: use `os.tmpdir()` to safely store `_karma_webpack_`

### PR DESCRIPTION
**Pull request by 8bitDesigner**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
From https://github.com/webpack-contrib/karma-webpack/issues/230:
> Any plugin trying to write to assets folder will fail because karma webpack rewrites webpackOptions.output like so.

``` javascript
webpackOptions.output.path = '/_karma_webpack_/' + indexPath;
webpackOptions.output.publicPath = '/_karma_webpack_/' + publicPath;
```

> Since that path /_karma_webpack_/... has never existed the plugin which tries to write to asset folder will fail with ENOENT can't open file error.

**What is the new behavior?**
Instead of using a `_karma_webpack_` directory in root, it the plugin now uses a `_karma_webpack_` directory from the system's temp folder.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the following...

* Impact:
* Migration path for existing applications:
* Github Issue(s) this is regarding:

**Other information**:

### CODE REVIEW

**Comment by 8bitDesigner** [comment]
@d3viant0ne, good catch; just rewrote that commit without the build files in `lib`.

**Comment by GitScrum** [comment]
@d3viant0ne approve ?

**Comment by bladedancer** [comment]
This is probably user error on my part but with 2.0.6 my tests are running fine. On 2.0.8 I get an error:

```
14 12 2017 21:04:38.094:DEBUG [middleware:source-files]: Requesting /tmp/_karma_webpack_/3.bundle.js /
14 12 2017 21:04:38.094:DEBUG [middleware:source-files]: Fetching /tmp/_karma_webpack_/3.bundle.js
14 12 2017 21:04:38.094:WARN [web-server]: 404: /tmp/_karma_webpack_/3.bundle.js
```

Code that seems to be triggering this is react-intl-loader:

```
const locales = {
	en: () => require('react-intl-loader?locale=en!./en.json'),
	es: () => require('react-intl-loader?locale=es!./es.json')
};
```
I'll dig into it more but if there's anything obvious that stands out then that would be a great help.

thanks

**Comment by GitScrum** [comment]
@bladedancer Hi, create new issue pleas. Thanks!

**Comment by sechel** [comment]
My test suite also breaks with this PR. The problem is that I have an elaborate webpack config that builds other stuff alongside the karma test bundle. If I run integration tests that depend on those other bundles I could access them under `<test-server-name>:port/_karma_webpack_/...`.  This is not possible anymore after this PR because now all resources are served from some not-guessable `/var/tmp/<some-random-stuff>.///` location.

**Comment by 8bitDesigner** [comment]
Hey mate, you should be able to get a reference to that folder using the node `os.tmpdir()` method, which is a more secure way of doing what you're trying to do. The former behaviour had karma-webpack writing to the system's root folder, which isn't allowed by most system configurations.

**Comment by sechel** [comment]
Yes, you are right. I ended up using the value `__webpack_public_path__` that is exposed by webpack and contains this path. This solves most of my problems I'm having with this change but not all. Unfortunately some of my tests, i.e., test driving OAuth2 consent flow, require a fixed URI. Here is the question: Why is the `publicPath` equal to the physical path? Can't one just use `/_karma_webpack_/` as public path and the tmp dir as `output.path`?

**Comment by lk77** [comment]
hello,

karma does not seems to serve files located in the folder : `/tmp/_karma_webpack_/`

**Pull request merged**
