### PR TITLE
Add support for file source maps

### PR DESCRIPTION
**Pull request by aaronjensen**
Addresses #51

### CODE REVIEW

**Comment by aaronjensen** [comment]
This currently only applies to when `optionsCount <= 1` (I'm not really sure what that is...) but I can adapt it to the other if this looks good.

**Comment by aaronjensen** [comment]
Ah... it looks like it's for supporting multiple webpack configs. It concatenates all of the output files... I'm not sure how that could work with sourcemaps. It probably didn't w/ the old method, did it?

We'd have to fetch all of the source maps and adjust the line numbers to deal w/ the concat, right?

**Comment by aaronjensen** [comment]
For anyone coming here, I published https://www.npmjs.com/package/karma-webpack-with-fast-source-maps for now until this is updated

**Comment by Dignifiedquire** [comment]
This looks really nice to me. Thanks @aaronjensen 
@sokra could you take a look when you have a moment please, and let me know if I'm okay to merge this.

**Comment by sokra** [comment]
It would be great if this also work for the `optionsCount > 1` case. Shouldn't be to complex to adjust it.

**Comment by aaronjensen** [comment]
@sokra @Dignifiedquire Thanks.

I did not really know how to test with `optionsCount > 1`. Am I right that we would have to concat all of the source maps and adjust line numbers?

Does anyone know why `cheap-module-inline-source-map` does not work w/ the current version?

**Comment by sokra** [comment]
> Am I right that we would have to concat all of the source maps and adjust line numbers?

Yes, but there are tools out there which do this for you. You can use the `source-map` lib, which is the lib `devtool: "source-map"` uses, or you can use the `source-list-map` lib, which is the lib `devtool: "cheap-source-map"` and variants uses.

```
source-map: 
SourceNode.fromStringWithSourceMap
  -> new SourceNode(..., [a, b, c])
  -> SourceNode.toStringWithSourceMap.

source-list-map:
fromStringWithSourceMap(...)
  -> SourceListMap.add
  -> SourceListMap.toStringWithSourceMap
```

**Comment by aaronjensen** [comment]
fyi @sokra I don't know how to progress on this because of #77 

I also don't know what multiple configurations is used for. Thanks!

**Comment by d3viant0ne** [comment]
@aaronjensen - What do you want to do here? We can resurrect this PR after we merge in all the code validations / es6 support or get the team to brainstorm a solution. Sourcemaps / Performance are on the hotlist once we have proper testing in place.

**Comment by aaronjensen** [comment]
@d3viant0ne Yes, that'd be great. I didn't feel comfortable with this change given the lack of coverage and my lack of understanding of multiple webpack configs, but it'd be great to get something like this merged in so my fork can go away.

**Comment by d3viant0ne** [comment]
That was unintentionally closed when I fixed the master branch. @aaronjensen next time you have 3/4 minutes free, ping me in slack.

**Comment by aaronjensen** [comment]
@d3viant0ne i pinged you on gitter, not sure if that's what you meant or if there's a webpack slack I don't know about

**Comment by mgol** [comment]
@d3viant0ne Why did you close it? I don't see a fix on `master`.

**Comment by d3viant0ne** [comment]
Fixing the master branch. This feature hasn't gone anywhere nor has the plan changed, @aaronjensen is a part of the webpack organization. This effort will be taken up again at the appropriate time.

**Comment by mgol** [comment]
OK, thanks for the update.

**Pull request closed without merging**
