### PR TITLE
chore(package): update `peerDependencies` (`webpack v3.0.0`)

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- [x] Chore

**Does this PR introduce a breaking change?**

- [x] No

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
Fixes #244

**Comment by viniciusffj** [comment]
Is there any change that this pr will get merged?

**Comment by lukeapage** [comment]
@d3viant0ne please can we get this merged and published?

**Comment by d3viant0ne** [comment]
`karma-webpack@2.0.4` is out on npm

**Pull request merged**
