### PR TITLE
fix(karma-webpack): allow `filename` and `chunkFilename` to be overridden (`config.output`)

### LINKED ISSUE #334: The `output.filename` should end with `.js`.
There are certain issues with your current config 
https://github.com/webpack-contrib/karma-webpack/blob/1ac16eaa7b11ee154a2127d4f03cbfd1a81533f6/src/karma-webpack.js#L65 

For instance the folks over at [`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin) filter all assets that do not end with `.js`, thus all `.html` files emitted stay empty when built alongside the test bundle using karma webpack.
Another thing is that `webpack-dev-middleware` doesn't recognize the mime type, e.g, when using a `typescript` `.ts` input file and this leads to other problems in browsers. One could solve this with a simple `mime: { 'text/javascript': ['ts'] }` but this seems hacky to me.

Anyway, I wanted to drop a line and see if we could get a discussion running on the matters.
Greetings
Stefan

### PR DESCRIPTION
**Pull request by Teamop**
### `Type`

- [x] Bugfix

### `Issues`

- Fixes #334

### `SemVer`

 - Fix (🏷 Patch)

### `Checklist`

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@Teamop Would you mind to open this PR against the `next` (v4.0.0) branch aswell ? :)

**Comment by Teamop** [comment]
@michael-ciniawsky  sure

**Comment by Teamop** [comment]
@michael-ciniawsky done, #339

**Comment by michael-ciniawsky** [comment]
Released in [`v3.0.1`](https://github.com/webpack-contrib/karma-webpack/releases/tag/v3.0.1) && [`v4.0.0-rc.0`](https://github.com/webpack-contrib/karma-webpack/releases/tag/v4.0.0-rc.0) 🎉

**Pull request merged**
