### PR TITLE
chore(package): update `webpack-dev-middleware` v1.12.0...2.0.6 (`dependencies`)

### LINKED ISSUE #314: Upgrade webpack-dev-middleware dependency
**I'm submitting a bug report**

**Webpack version:**
4.0.1

**Webpack Karma version**:
2.0.7

**Karma version**:
2.0.0

**Please tell us about your environment:**
OSX 10.13.3

**Browser:** Chrome 64, Safari 11.0.3

**Current behavior:**
Currently karma-webpack has `webpack-dev-middleware` 1.12.0 listed as a dependency.  This is two major versions behind the current release (3.0.0).

Despite #301 having added webpack v4.x as a `peerDependency`, installing this alongside webpack 4.0.1 will still display warnings because `webpack-dev-middleware` does _not_ list webpack 4.x as a valid peer.  `yarn check` will actually throw an error because of this.

This is the primary roadblock for my project to upgrade to webpack v4.  Our CI will not accept anything for which `yarn check` produces an error.

**Expected/desired behavior:**

karma-webpack should use `webpack-dev-middleware` v2.0.6 which has compatibility with webpack v2.2-4.0, or release a new major version that uses `webpack-dev-middleware` v3.0.0 and drops compatibility with webpack 2 and 3.

* **What is the motivation / use case for changing the behavior?**

wanting to use webpack 4 without warnings in my console when installing packages

### PR DESCRIPTION
**Pull request by limonte**
Fixes #314 

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:
  - Update `webpack-dev-middleware` dependency

**Does this PR introduce a breaking change?**
- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the following...

* Impact: the new major release is required since `webpack ^1.0.0` support has been dropped in `webpack-dev-middleware ^2.0.0`

**Other information**:

- https://github.com/webpack/webpack-dev-middleware/releases/tag/v2.0.0

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
What's the exact issue you're facing and would #315 fix your it. Note that #315 requires `webpack >= v4.0.0` && `node >= v6.0.0`. If that's sufficient I would favor #315 over this PR instead

**Comment by limonte** [comment]
> What's the exact issue you're facing and would #315 fix it?

Oh, I didn't notice #315, apologies. Basically, it's the same, but as you said

>  #315 requires webpack >= v4.0.0

and this PR still support webpack 2 and 3.

#315 will work for me personally (we're trying to fix flaky https://github.com/sweetalert2/sweetalert2/issues/986) so I'm okay to close this PR in favor of #315

**Comment by michael-ciniawsky** [comment]
It should eventually be possible to support `webpack =< v4.0.0` in #315 aswell, depending on `webpack-dev-middleware` `v2.0.0 <=> v3.0.0` (But I think `v3.0.0` is `webpack >= v4.0.0` aswell 😭) so maybe we need to majors version bumps then 😒

**Comment by limonte** [comment]
> so maybe we need to majors version bumps then

I don't see anything wrong with two major bumps in this case. With proper release titles and release notes devs will appreciate two different majors for webpack `^2.0.0 - ^4.0.0` projects and webpack `^4.0.0` projects.

**Comment by michael-ciniawsky** [comment]
Released in [v3.0.0](https://github.com/webpack-contrib/karma-webpack/releases/tag/v3.0.0) 🎉  Thx

**Pull request merged**
