### PR TITLE
fix(karma-webpack):  normalize paths to be compatible with windows

### PR DESCRIPTION
**Pull request by igomezal**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Karma runner didn't work with the v5.0.0-alpha.1 of this preprocessor on Windows machines.

### Additional Info

This solves https://github.com/webpack-contrib/karma-webpack/issues/396

### CODE REVIEW

**Comment by anoblet** [comment]
I can confirm this is working.

**Comment by ggriffithsIDBS** [comment]
I commented on https://github.com/open-wc/open-wc/issues/204 I used their provided karma configuration, against "^5.0.0-alpha.0" and patched my node_modules with the code from this pr on Windows 10, my tests worked! 💯

**Comment by daKmoR** [comment]
@matthieu-foucault could you pls release a new 5.x alpha version with this fix?

would help us a lot 🤗 as we apparently have more windows users then expected 🙈

**Comment by matthieu-foucault** [comment]
Published under the `@dev` tag.

**Pull request merged**
